### ISSUE TITLE
2.2 웹과 HTTP 단어 추가

### ISSUE THREAD

**Issue by iyeaaa** [IT-Book-Organization/Computer-Networking_A-Top-Down-Approach#17]
2.2.1 웹페이지 섹션에서

"예를 들어, 웹 페이지가 HTML 텍스트와 **5개의** JPEG 이미지로 구성되어 있으면, 이 페이지는 6개의 객체를 갖는다" 로 수정해야할것 같습니다.

"5개"가 빠졌어요.

**Comment by eunaJung01** [comment]
반영했습니다! 감사합니다 👍
